services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: CORS_ORIGIN
        value: https://expense-tracker-client-ulm2.onrender.com/

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker
    user: expense_tracker_user
    plan: free
